(progn
  (let ((functions
         (eval '(let ((prefix "captured-prefix"))
                  (list (lambda (left right)
                          (and (equal prefix "captured-prefix")
                               (equal left right)))
                        (lambda (_key) (length prefix))))
               t)))
    (define-hash-table-test 'capture-check (car functions) (cadr functions)))
  (let* ((old (make-hash-table :test 'capture-check :weakness 'key))
         (key (copy-sequence "retained-key")))
    (puthash key 'old-value old)
    (define-hash-table-test 'capture-check
      (lambda (_left _right) nil) (lambda (_key) 39))
    (let ((new (make-hash-table :test 'capture-check))
          (copy (copy-hash-table old)))
      (puthash key 'new-value new)
      (put 'capture-check 'hash-table-test nil)
      (garbage-collect)
      (let ((before (list (gethash (copy-sequence key) old 'absent)
                          (gethash (copy-sequence key) new 'absent)
                          (gethash (copy-sequence key) copy 'absent)
                          (eq (hash-table-test copy) 'capture-check)
                          (eq (hash-table-weakness copy) 'key))))
        (clrhash copy)
        (puthash key 'copied-value copy)
        (remhash (copy-sequence key) old)
        (append before
                (list (gethash (copy-sequence key) copy 'absent)
                      (hash-table-count old) (hash-table-count new)
                      (hash-table-count copy)))))))
