(progn
  (require 'comp)
  (let (results)
    (dolist (name '(positioned-read-native renamed-position-read-native))
      (let* ((source (make-temp-file (symbol-name name) nil ".el"))
             (output (make-temp-file "positioned-native-output-" t))
             (comp-no-spawn nil)
             (comp-running-batch-compilation t)
             (native-comp-jit-compilation nil)
             (symbols-with-pos-enabled t)
             (definition
              `(defun ,name (object bare position callback)
                 (let ((again (position-symbol bare position))
                       (base (bare-symbol object))
                       (at (symbol-with-pos-pos object)))
                   (garbage-collect)
                   (and (eq base bare)
                        (= at position)
                        (eq (type-of object) 'symbol-with-pos)
                        (symbol-with-pos-p object)
                        (= (funcall callback object) position)
                        (let ((symbols-with-pos-enabled nil))
                          (and (not (symbolp object))
                               (eq object object)
                               (not (eq object again))
                               (not (eql object again))
                               (equal object again)
                               (equal-including-properties object again)))
                        (let ((symbols-with-pos-enabled t))
                          (and (symbolp object)
                               (eq object bare)
                               (eql object bare)
                               (equal object bare)
                               (eq object again)
                               (= (sxhash-eq object) (sxhash-eq bare))))))))
             (valid t)
             (count 0))
        (unwind-protect
            (progn
              (eval definition t)
              (let* ((interpreted (symbol-function name))
                     (bytecode (byte-compile interpreted))
                     (callback (make-interpreted-closure
                                '(object) '((symbol-with-pos-pos object)) '(t) nil)))
                (with-temp-file source
                  (insert ";;; -*- lexical-binding: t -*-\n")
                  (prin1 definition (current-buffer)))
                (native-elisp-load
                 (native-compile source (expand-file-name "positioned.eln" output)))
                (let ((native (symbol-function name)))
                  (dolist (function (list interpreted bytecode native))
                    (dolist (bare (list nil t name (make-symbol "shared-position-name")))
                      (dolist (position '(-4 0 79))
                        (setq count (1+ count))
                        (unless (funcall function (position-symbol bare position)
                                         bare position callback)
                          (setq valid nil)))))
                  (push (list (interpreted-function-p interpreted)
                              (byte-code-function-p bytecode)
                              (native-comp-function-p native)
                              valid count)
                        results))))
          (fmakunbound name)
          (delete-file source)
          (delete-directory output t))))
    (nreverse results)))
