(let ((read-symbol-shorthands '(("s-" . "expanded-")))
      (symbols-with-pos-enabled nil))
  (mapcar (lambda (reader)
            (mapcar (lambda (source)
                      (condition-case error
                          (let* ((object (funcall reader source))
                                 (bare (bare-symbol object)))
                            (list (symbol-name bare)
                                  (symbol-with-pos-p object)
                                  (and (symbol-with-pos-p object)
                                       (symbol-with-pos-pos object))
                                  (eq bare (intern (symbol-name bare)))))
                        (error (car error))))
                    '("#:s-name" "#:nil" "#:t" "#:123" "#:")))
          '(read read-positioning-symbols)))
