(let ((symbols-with-pos-enabled nil)
      (read-symbol-shorthands '(("s-" . "expanded-"))))
  (let* ((form (read-positioning-symbols
                "([s-α #_s-raw t nil] #1=(s-β . #1#) #s(tag s-value) 's-quote)"))
         (vector (nth 0 form))
         (cycle (nth 1 form))
         (record (nth 2 form))
         (quoted (nth 3 form))
         (describe (lambda (object)
                     (if (symbol-with-pos-p object)
                         (list (symbol-name (bare-symbol object))
                               (symbol-with-pos-pos object))
                       object)))
         (private (obarray-make))
         (bare (intern "reader-private-name" private))
         (positioned (let ((obarray private))
                       (read-positioning-symbols "reader-private-name"))))
    (list (mapcar describe (append vector nil))
          (list (funcall describe (car cycle)) (eq cycle (cdr cycle)))
          (list (recordp record) (funcall describe (aref record 0))
                (funcall describe (aref record 1)))
          (list (car quoted) (funcall describe (cadr quoted)))
          (list (eq (bare-symbol positioned) bare)
                (symbol-with-pos-pos positioned)
                (eq (intern-soft "reader-private-name" private) bare)))))
