(let* ((original (current-buffer))
       (late (get-buffer-create " value-order-zeta"))
       (early (get-buffer-create " value-order-alpha"))
       (late-marker (make-marker))
       (early-marker (make-marker))
       (free-one (make-marker))
       (free-two (make-marker))
       results)
  (unwind-protect
      (progn
        (set-buffer late)
        (insert "abcdefghijklmnopqrst")
        (set-buffer early)
        (insert "ABCDEFGHIJKLMNOPQRST")
        (set-marker late-marker 13 late)
        (set-marker early-marker 12 early)
        (setq results
              (list (list (value< early late) (value< late early)
                          (value< early-marker late-marker)
                          (value< free-one early-marker)
                          (value< early-marker free-one)
                          (value< (vector free-one 1) (vector free-two 2)))))
        (set-buffer late)
        (rename-buffer " value-order-00-renamed")
        (setq results
              (cons (list (value< late early) (value< late-marker early-marker))
                    results))
        (kill-buffer late)
        (setq results
              (cons (list (value< late early)
                          (value< late-marker early-marker)
                          (value< early-marker late-marker))
                    results))
        (kill-buffer early)
        (cons (list (value< late early) (value< early late)
                    (value< (vector late 1) (vector early 2)))
              results))
    (set-buffer original)
    (kill-buffer late)
    (kill-buffer early)))
