;;; core_runtime_perf.el --- Shared runtime measurement bodies -*- lexical-binding: t; -*-

;; Both editors load this exact source through their ordinary command line.
;; Preparation, compilation, result checks and reporting are outside body time.
;; Upstream test bodies retain their own assertions as part of their work.

(require 'cl-lib)
(require 'json)
(require 'bytecomp)

(defun core-perf-lexical-loop (n)
  (let ((i 0) (sum 0))
    (while (< i n)
      (let ((value (and (> i -1) i)))
        (if value (setq sum (1+ sum))))
      (setq i (1+ i)))
    sum))

(defalias 'core-perf-dynamic-loop
  (eval '(lambda (n)
           (let ((i 0) (sum 0))
             (while (< i n)
               (let ((value (and (> i -1) i)))
                 (if value (setq sum (1+ sum))))
               (setq i (1+ i)))
             sum))
        nil))

(defun core-perf-add (a b) (+ a b))

(defun core-perf-calls (n)
  (let ((i 0) (sum 0))
    (while (< i n)
      (setq sum (core-perf-add sum i) i (1+ i)))
    sum))

(defun core-perf-byte-add (a b) (+ a b))

(defun core-perf-byte-calls (n)
  (let ((i 0) (sum 0))
    (while (< i n)
      (setq sum (core-perf-byte-add sum i) i (1+ i)))
    sum))

(defun core-perf-byte-native (n)
  (let ((i 0) (sum 0))
    (while (< i n)
      (setq sum (+ sum (comp-tests-fixnum-1-plus-f i)) i (1+ i)))
    sum))

(defun core-perf-callback () 43)

(defun core-perf-conses (n)
  (let ((i 0) (items nil))
    (while (< i n)
      (setq items (cons i items) i (1+ i)))
    items))

(defun core-perf-mode (function)
  (let ((definition (if (symbolp function) (symbol-function function) function)))
    (cond ((native-comp-function-p definition) "native")
          ((byte-code-function-p definition) "bytecode")
          ((subrp definition) "primitive")
          ((and (functionp definition) (not (subrp definition))) "interpreted")
          (t (error "Not an executable function: %S" function)))))

(defun core-perf-require-mode (function expected)
  (let ((actual (core-perf-mode function)))
    (unless (equal actual expected)
      (error "%S must execute as %s, observed %s" function expected actual))
    (cons (symbol-name function) actual)))

(defun core-perf-equal-check (expected)
  (lambda (actual)
    (unless (equal actual expected)
      (error "Incorrect workload result: %S; expected %S" actual expected))
    (prin1-to-string actual)))

(defun core-perf-prepare (case-id n source-root native-file)
  "Return (BODY CHECK MODES) without doing any measured work."
  (let ((mode-evidence nil))
    (when (string-match-p "native" case-id)
      (unless (and native-file (file-readable-p native-file))
        (error "Missing explicitly compiled native artifact"))
      (load native-file nil nil t))
    (pcase case-id
      ((or "interpreted-lexical" "interpreted-dynamic" "interpreted-calls")
       (let ((function (pcase case-id
                         ("interpreted-lexical" 'core-perf-lexical-loop)
                         ("interpreted-dynamic" 'core-perf-dynamic-loop)
                         (_ 'core-perf-calls))))
         (push (core-perf-require-mode function "interpreted") mode-evidence)
         (when (equal case-id "interpreted-calls")
           (push (core-perf-require-mode 'core-perf-add "interpreted") mode-evidence))
         (list (lambda () (funcall function n))
               (core-perf-equal-check
                (if (equal case-id "interpreted-calls") (/ (* n (1- n)) 2) n))
               mode-evidence)))
      ("bytecode-calls"
       (dolist (function '(core-perf-byte-add core-perf-byte-calls))
         (byte-compile function)
         (push (core-perf-require-mode function "bytecode") mode-evidence))
       (list (lambda () (core-perf-byte-calls n))
             (core-perf-equal-check (/ (* n (1- n)) 2)) mode-evidence))
      ("native-execution"
       (push (core-perf-require-mode 'comp-tests-fib-f "native") mode-evidence)
       (list (lambda ()
               (let ((sum 0))
                 (dotimes (_ n) (setq sum (+ sum (comp-tests-fib-f 28))))
                 sum))
             (core-perf-equal-check (* n 317811)) mode-evidence))
      ((or "interpreted-to-native" "bytecode-to-native")
       (push (core-perf-require-mode 'comp-tests-fixnum-1-plus-f "native") mode-evidence)
       (if (equal case-id "bytecode-to-native")
           (progn
             (byte-compile 'core-perf-byte-native)
             (push (core-perf-require-mode 'core-perf-byte-native "bytecode") mode-evidence))
         (push (core-perf-require-mode 'core-perf-byte-native "interpreted") mode-evidence))
       (list (lambda () (core-perf-byte-native n))
             (core-perf-equal-check (/ (* n (1+ n)) 2)) mode-evidence))
      ((or "native-to-interpreted" "native-to-bytecode")
       (push (core-perf-require-mode 'comp-tests-catch-f "native") mode-evidence)
       (let ((callback-mode (if (equal case-id "native-to-bytecode") "bytecode" "interpreted")))
         (when (equal callback-mode "bytecode") (byte-compile 'core-perf-callback))
         (push (core-perf-require-mode 'core-perf-callback callback-mode) mode-evidence))
       (list (lambda ()
               (let ((sum 0))
                 (dotimes (_ n)
                   (setq sum (+ sum (comp-tests-catch-f #'core-perf-callback))))
                 sum))
             (core-perf-equal-check (* n 43)) mode-evidence))
      ("cons-allocation"
       (list (lambda () (core-perf-conses n))
             (lambda (items)
               ;; Inspect every cell after timing, not just a length or a canned sum.
               (let ((expected (1- n)))
                 (while items
                   (unless (and (consp items) (eql (car items) expected))
                     (error "Incorrect cons chain at index %S" expected))
                   (setq expected (1- expected) items (cdr items)))
                 (unless (= expected -1) (error "Truncated cons chain")))
               (format "descending-cons-chain/%d" n))
             (list (core-perf-require-mode 'core-perf-conses "interpreted"))))
      ("list-traversal"
       (let ((items (number-sequence 1 128)))
         (list (lambda ()
                 (let ((sum 0))
                   (dotimes (_ n)
                     (let ((cursor items))
                       (while cursor
                         (setq sum (+ sum (car cursor)) cursor (cdr cursor)))))
                   sum))
               (core-perf-equal-check (* n 8256))
               '(("body" . "interpreted")))))
      ("mapcar"
       (let ((items (number-sequence 1 100000)))
         (list (lambda ()
                 (let (result)
                   (dotimes (_ n) (setq result (mapcar #'1+ items)))
                   result))
               (lambda (result)
                 (unless (equal result (number-sequence 2 100001))
                   (error "Incorrect mapcar chain"))
                 "ascending-mapcar-chain/100000")
               (list (core-perf-require-mode 'mapcar "primitive")))))
      ("explicit-gc"
       (let ((live (core-perf-conses 100000)))
         (list (lambda () (dotimes (_ n) (garbage-collect)) live)
               (lambda (result)
                 (unless (eq result live) (error "GC lost live root identity"))
                 (unless (equal result (reverse (number-sequence 0 99999)))
                   (error "GC corrupted the live cons chain"))
                 "live-cons-chain/100000")
               (list (core-perf-require-mode 'garbage-collect "primitive")))))
      ("upstream-sort"
       (load (expand-file-name "lisp/sort.el" source-root) nil nil t)
       (load (expand-file-name "test/lisp/sort-tests.el" source-root) nil nil t)
       ;; Fixed nonrandom input, passed to the unchanged upstream helper.
       (let ((words (mapcar (lambda (i) (format "%05d-%05d" (% (* i 811) 1024) i))
                            (number-sequence 0 1023))))
         (list (lambda ()
                 (dotimes (_ n)
                   (sort-tests--insert-words-sort-and-compare words "\n" #'sort-lines nil #'string<)
                   (sort-tests--insert-words-sort-and-compare words "\n" #'sort-lines t #'string<))
                 (* n 2))
               (core-perf-equal-check (* n 2))
       (list (core-perf-require-mode 'sort-tests--insert-words-sort-and-compare "interpreted")
                     (core-perf-require-mode 'sort-lines "interpreted")))))
      ("upstream-undo"
       ;; The dump can preload native simple.el. Reload its unchanged bytecode
       ;; explicitly, with load-no-native set by the common command line.
       (load (expand-file-name "lisp/simple.elc" source-root) nil nil t)
       (load (expand-file-name "test/src/undo-tests.el" source-root) nil nil t)
       (let ((names '(undo-test0 undo-test1 undo-test2 undo-test5)))
         (list (lambda ()
                 (let (results)
                   (dotimes (_ n)
                     (dolist (name names)
                       (push (ert-run-test (ert-get-test name)) results)))
                   results))
               (lambda (results)
                 (unless (= (length results) (* n (length names)))
                   (error "Incomplete upstream undo inventory"))
                 (dolist (result results)
                   (unless (ert-test-passed-p result)
                     (error "Upstream undo failed: %S" result)))
                 (format "passed/%d" (length results)))
               (append
                (mapcar (lambda (name)
                          (cons (symbol-name name) (core-perf-mode (ert-test-body (ert-get-test name)))))
                        names)
                (mapcar (lambda (name) (core-perf-require-mode name "bytecode"))
                        '(undo undo-more primitive-undo))))))
      ("upstream-bindat"
       (load (expand-file-name "lisp/emacs-lisp/bindat.el" source-root) nil nil t)
       (load (expand-file-name "test/lisp/emacs-lisp/bindat-tests.el" source-root) nil nil t)
       (list (lambda ()
               (let (result)
                 (dotimes (_ n)
                   (setq result (bindat-unpack packet-bindat-spec
                                               (bindat-pack packet-bindat-spec struct-bindat))))
                 result))
             (core-perf-equal-check struct-bindat)
             (mapcar (lambda (name) (cons (symbol-name name) (core-perf-mode name)))
                     '(bindat-pack bindat-unpack))))
      (_ (error "Unknown core workload: %S" case-id)))))

(defun core-perf-allocation-counters ()
  ;; Preserve the actual diagnostic if the starting runtime lacks counters.
  ;; Final certification requires counters; absence is never interpreted as zero.
  (condition-case error
      (let ((counts (memory-use-counts)))
        (unless (and (= (length counts) 7) (cl-every #'natnump counts))
          (error "Invalid memory-use-counts: %S" counts))
        `(("status" . "available") ("counts" . ,(vconcat counts))))
    (error `(("status" . "unavailable") ("error" . ,(prin1-to-string error))))))

(defun core-perf-run (case-id n warmup samples source-root native-file output)
  (unless (and (natnump warmup) (integerp samples) (> samples 0)
               (integerp n) (> n 0))
    (error "Invalid core performance parameters"))
  (let* ((prepared (core-perf-prepare case-id n source-root native-file))
         (body (nth 0 prepared))
         (check (nth 1 prepared))
         (observations nil))
    (dotimes (index (+ warmup samples))
      (let* ((heap-before (garbage-collect))
             (allocation-before (core-perf-allocation-counters))
             (collections-before gcs-done)
             (gc-time-before gc-elapsed)
             (started (float-time))
             (result (funcall body))
             (seconds (- (float-time) started))
             (collections (- gcs-done collections-before))
             (gc-seconds (- gc-elapsed gc-time-before))
             (allocation-after (core-perf-allocation-counters))
             (checked (funcall check result))
             (observation
              `(("index" . ,index) ("warmup" . ,(if (< index warmup) t :json-false))
                ("seconds" . ,seconds) ("gc_count" . ,collections) ("gc_seconds" . ,gc-seconds)
                ("result" . ,checked)
                ("allocation_before" . ,allocation-before) ("allocation_after" . ,allocation-after)
                ("heap_before" . ,(prin1-to-string heap-before)))))
        (unless (and (> seconds 0) (>= collections 0) (>= gc-seconds 0))
          (error "Invalid measured interval: %S" observation))
        (when (and (equal case-id "explicit-gc") (< collections n))
          (error "Explicit collections were omitted"))
        (princ (concat "CORE-PERF-SAMPLE " (json-encode observation) "\n"))
        (push observation observations)))
    (with-temp-file output
      (insert
       (json-encode
        `(("format_version" . 1) ("status" . "completed")
          ("case_id" . ,case-id) ("n" . ,n) ("warmup" . ,warmup) ("samples" . ,samples)
          ("modes" . ,(cons (cons "driver" (core-perf-mode body)) (nth 2 prepared)))
          ("gc_cons_threshold" . ,gc-cons-threshold) ("gc_cons_percentage" . ,gc-cons-percentage)
          ("emacs_version" . ,emacs-version) ("system_configuration" . ,system-configuration)
          ("native_available" . ,(if (native-comp-available-p) t :json-false))
          ("observations" . ,(vconcat (nreverse observations)))))))))

(provide 'core_runtime_perf)
;;; core_runtime_perf.el ends here
