;;; generate_builtin_arities.el --- Generate GNU primitive arity manifest -*- lexical-binding: t; -*-

;; Usage:
;;   emacs -Q --batch -l compat/generate_builtin_arities.el \
;;     --eval '(emaxx-generate-builtin-arities "src/lisp" "src/lisp/primitives/generated_builtin_arities.rs")'

;;; Code:

(require 'cl-lib)

(defun emaxx--rust-string-literal (value)
  "Return VALUE encoded as a single-line Rust string literal."
  (concat
   "\""
   (mapconcat
    (lambda (character)
      (pcase character
        (?\\ "\\\\")
        (?\" "\\\"")
        (?\n "\\n")
        (?\r "\\r")
        (?\t "\\t")
        (?\0 "\\0")
        ((pred (lambda (value) (or (< value 32) (= value 127))))
         (format "\\u{%x}" character))
        (_ (char-to-string character))))
    value "")
   "\""))

(defun emaxx--native-dispatch-source-p (file source-root)
  "Return non-nil when FILE owns native dispatch names below SOURCE-ROOT."
  (let ((relative (file-relative-name file source-root)))
    (or (member relative
                '("primitives.rs"
                  "primitives/ccl.rs"
                  "primitives/numeric_time.rs"
                  "sqlite.rs"))
        (string-prefix-p "primitives/dispatch" relative))))

(defun emaxx-generate-builtin-arities (source-root output-file)
  "Write GNU subr arities mentioned below SOURCE-ROOT to OUTPUT-FILE.

Emaxx's dispatchers contain every native function name as a Rust string
literal.  Intersecting those literals with the running GNU Emacs's subrs
keeps the generated table complete without teaching the generator about the
layout of individual dispatcher modules."
  (let ((seen (make-hash-table :test #'equal))
        entries interactive-names interactive-entries)
    (dolist (file (directory-files-recursively source-root "\\.rs\\'"))
      ;; Only native dispatch ownership files participate.  Test strings,
      ;; helper operation tables, and generated inventories must never make a
      ;; missing GNU primitive appear implemented on regeneration.
      (when (emaxx--native-dispatch-source-p file source-root)
        (with-temp-buffer
          (insert-file-contents file)
          (goto-char (point-min))
          (while (re-search-forward "\"\\([^\"\n]+\\)\"" nil t)
            (let* ((name (match-string-no-properties 1))
                   (symbol (intern-soft name)))
              (when (and symbol
                         (not (gethash name seen))
                         (fboundp symbol)
                         (subrp (symbol-function symbol)))
                (let ((function (symbol-function symbol)))
                  (pcase-let ((`(,minimum . ,maximum)
                               (subr-arity function)))
                    (when (and (integerp minimum)
                               (or (integerp maximum)
                                   (memq maximum '(many unevalled))))
                      (puthash name t seen)
                      (push (list name minimum maximum) entries)
                      (when-let ((interactive (interactive-form function)))
                        (let ((form (prin1-to-string interactive)))
                          (push name interactive-names)
                          ;; Native-compiled dumped Lisp can expose an
                          ;; `(interactive (byte-code ...))' form containing
                          ;; raw control bytes.  Record command identity for
                          ;; all such functions, but only embed forms that are
                          ;; safe Rust source text.
                          (unless (string-match-p
                                   "[\0-\x08\x0b\x0c\x0e-\x1f]" form)
                            (push (list name form)
                                  interactive-entries)))))))))))))
    (setq entries (sort entries (lambda (left right)
                                  (string< (car left) (car right)))))
    (setq interactive-entries
          (sort interactive-entries
                (lambda (left right) (string< (car left) (car right)))))
    (setq interactive-names (sort interactive-names #'string<))
    (with-temp-file output-file
      (insert "// @generated by compat/generate_builtin_arities.el using GNU Emacs.\n")
      (insert "// Regenerate when the compatibility oracle version changes.\n\n")
      (insert "#[rustfmt::skip]\n")
      (insert "const GENERATED_BUILTIN_ARITIES: &[(&str, i64, i64)] = &[\n")
      (dolist (entry entries)
        (pcase-let ((`(,name ,minimum ,maximum) entry))
          (insert (format "    (%S, %d, %d),\n"
                          name minimum
                          (cond ((integerp maximum) maximum)
                                ((eq maximum 'many) -1)
                                (t -2))))))
      (insert "];\n\n")
      (insert "pub(super) fn generated_builtin_arity(name: &str) -> Option<(i64, i64)> {\n")
      (insert "    let index = GENERATED_BUILTIN_ARITIES\n")
      (insert "        .binary_search_by_key(&name, |(candidate, _, _)| *candidate)\n")
      (insert "        .ok()?;\n")
      (insert "    let (_, minimum, maximum) = GENERATED_BUILTIN_ARITIES[index];\n")
      (insert "    Some((minimum, maximum))\n")
      (insert "}\n\n")
      (insert "#[rustfmt::skip]\n")
      (insert "const GENERATED_BUILTIN_COMMANDS: &[&str] = &[\n")
      (dolist (name interactive-names)
        (insert (format "    %S,\n" name)))
      (insert "];\n\n")
      (insert "pub(super) fn generated_builtin_command_p(name: &str) -> bool {\n")
      (insert "    GENERATED_BUILTIN_COMMANDS.binary_search(&name).is_ok()\n")
      (insert "}\n\n")
      (insert "#[rustfmt::skip]\n")
      (insert "const GENERATED_BUILTIN_INTERACTIVE_FORMS: &[(&str, &str)] = &[\n")
      (dolist (entry interactive-entries)
        (pcase-let ((`(,name ,form) entry))
          (insert (format "    (%S, %s),\n"
                          name
                          (emaxx--rust-string-literal form)))))
      (insert "];\n\n")
      (insert "pub(super) fn generated_builtin_interactive_form(name: &str) -> Option<&'static str> {\n")
      (insert "    let index = GENERATED_BUILTIN_INTERACTIVE_FORMS\n")
      (insert "        .binary_search_by_key(&name, |(candidate, _)| *candidate)\n")
      (insert "        .ok()?;\n")
      (insert "    Some(GENERATED_BUILTIN_INTERACTIVE_FORMS[index].1)\n")
      (insert "}\n"))))

(provide 'generate_builtin_arities)

;;; generate_builtin_arities.el ends here
