;;; generate_gnu_c_primitive_manifest.el --- Inventory GNU C primitives -*- lexical-binding: t; -*-

;; Usage (run with the oracle binary built from UPSTREAM-SRC):
;;
;;   /path/to/emacs/src/emacs -Q --batch \
;;     -l compat/generate_gnu_c_primitive_manifest.el \
;;     --eval '(emaxx-generate-gnu-c-primitive-manifest
;;               "/path/to/emacs/src"
;;               "src/lisp/primitives/generated_gnu_c_primitives.rs")'

;;; Code:

(require 'cl-lib)

(defun emaxx--gnu-c-defuns (source-root)
  "Return sorted GNU DEFUN entries below SOURCE-ROOT.

Each entry is (NAME . ORIGINS), where ORIGINS is a sorted list of source
paths relative to SOURCE-ROOT.  Reading the C source instead of enumerating
all runtime subrs excludes native-compiled Lisp functions."
  (let ((origins (make-hash-table :test #'equal)))
    (dolist (file (directory-files-recursively source-root "\\.c\\'"))
      (with-temp-buffer
        (insert-file-contents file)
        (goto-char (point-min))
        (while (re-search-forward
                "\\_<DEFUN\\(?:[[:space:]\n\r]\\)*(\\(?:[[:space:]\n\r]\\)*\"\\([^\"]+\\)\""
                nil t)
          (let* ((name (match-string-no-properties 1))
                 (relative (file-relative-name file source-root)))
            (cl-pushnew relative (gethash name origins) :test #'equal)))))
    (let (entries)
      (maphash
       (lambda (name files)
         (push (cons name (sort files #'string<)) entries))
       origins)
      (sort entries (lambda (left right) (string< (car left) (car right)))))))

(defun emaxx--gnu-c-runtime-contract (name)
  "Return NAME's runtime C-subr contract, or nil when not built on this host."
  (let ((symbol (intern-soft name)))
    (when (and symbol
               (fboundp symbol)
               (subrp (symbol-function symbol)))
      (pcase-let ((`(,minimum . ,maximum)
                   (subr-arity (symbol-function symbol))))
        (when (and (integerp minimum)
                   (or (integerp maximum)
                       (memq maximum '(many unevalled))))
          (list minimum
                (cond ((integerp maximum) maximum)
                      ((eq maximum 'many) -1)
                      (t -2))
                (commandp symbol)
                (special-form-p symbol)))))))

(defun emaxx-generate-gnu-c-primitive-manifest (source-root output-file)
  "Write GNU C primitive contracts from SOURCE-ROOT to OUTPUT-FILE.

The generated file records every source-level DEFUN and marks primitives
excluded by this host's build as unavailable.  Emaxx's Rust tests intersect
this authoritative list with its own native dispatcher, so adding a Rust
mirror without surface-contract coverage fails the fast suite."
  (let* ((source-root (file-truename source-root))
         (entries (emaxx--gnu-c-defuns source-root))
         (available 0))
    (with-temp-file output-file
      (insert "// @generated by compat/generate_gnu_c_primitive_manifest.el.\n")
      (insert "// Source contract: GNU Emacs 30.2 src/*.c DEFUN declarations.\n")
      (insert "// Regenerate when the compatibility oracle version/configuration changes.\n\n")
      (insert "#[cfg_attr(not(test), allow(dead_code))]\n")
      (insert "#[derive(Clone, Copy, Debug)]\n")
      (insert "pub(crate) struct GnuCPrimitiveContract {\n")
      (insert "    pub(crate) name: &'static str,\n")
      (insert "    pub(crate) arity: Option<(i64, i64)>,\n")
      (insert "    pub(crate) command: bool,\n")
      (insert "    pub(crate) special_form: bool,\n")
      (insert "    pub(crate) origins: &'static str,\n")
      (insert "}\n\n")
      (insert "#[rustfmt::skip]\n")
      (insert "pub(crate) const GNU_C_PRIMITIVES: &[GnuCPrimitiveContract] = &[\n")
      (dolist (entry entries)
        (let* ((name (car entry))
               (origins (string-join (cdr entry) ","))
               (contract (emaxx--gnu-c-runtime-contract name)))
          (when contract
            (setq available (1+ available)))
          (insert
           (if contract
               (pcase-let ((`(,minimum ,maximum ,command ,special-form) contract))
                 (format
                  "    GnuCPrimitiveContract { name: %S, arity: Some((%d, %d)), command: %s, special_form: %s, origins: %S },\n"
                  name minimum maximum
                  (if command "true" "false")
                  (if special-form "true" "false")
                  origins))
             (format
              "    GnuCPrimitiveContract { name: %S, arity: None, command: false, special_form: false, origins: %S },\n"
              name origins)))))
      (insert "];\n\n")
      (insert "#[cfg_attr(not(test), allow(dead_code))]\n")
      (insert (format
               "pub(crate) const GNU_C_PRIMITIVE_SOURCE_COUNT: usize = %d;\n"
               (length entries)))
      (insert "#[cfg_attr(not(test), allow(dead_code))]\n")
      (insert (format
               "pub(crate) const GNU_C_PRIMITIVE_AVAILABLE_COUNT: usize = %d;\n"
               available))
      (insert "\npub(crate) fn generated_gnu_c_primitive_available(name: &str) -> Option<bool> {\n")
      (insert "    let index = GNU_C_PRIMITIVES\n")
      (insert "        .binary_search_by_key(&name, |contract| contract.name)\n")
      (insert "        .ok()?;\n")
      (insert "    Some(GNU_C_PRIMITIVES[index].arity.is_some())\n")
      (insert "}\n"))))

(provide 'generate_gnu_c_primitive_manifest)

;;; generate_gnu_c_primitive_manifest.el ends here
