;;; generate_gnu_c_defsym_manifest.el --- Inventory GNU C DEFSYMs -*- lexical-binding: t; -*-

;; Usage (any Emacs; the scan is purely textual):
;;
;;   /path/to/emacs/src/emacs -Q --batch \
;;     -l compat/generate_gnu_c_defsym_manifest.el \
;;     --eval '(emaxx-generate-gnu-c-defsym-manifest
;;               "/path/to/emacs/src"
;;               "src/lisp/primitives/generated_gnu_c_defsyms.rs")'

;;; Code:

(require 'cl-lib)

(defun emaxx--gnu-c-defsyms (source-root)
  "Return sorted GNU DEFSYM entries below SOURCE-ROOT.

Each entry is (NAME . ORIGINS), where ORIGINS is a sorted list of source
paths relative to SOURCE-ROOT.  This is a source-level contract like the
DEFUN manifest: which of these symbol registrations a particular build
performs is decided by the registration site from the DEFUN manifest's
availability facts, not here."
  (let ((origins (make-hash-table :test #'equal)))
    (dolist (file (directory-files-recursively source-root "\\.c\\'"))
      (with-temp-buffer
        (insert-file-contents file)
        (goto-char (point-min))
        (while (re-search-forward
                "\\_<DEFSYM\\(?:[[:space:]\n\r]\\)*(\\(?:[[:space:]\n\r]\\)*Q[A-Za-z0-9_]+\\(?:[[:space:]\n\r]\\)*,\\(?:[[:space:]\n\r]\\)*\"\\([^\"]+\\)\""
                nil t)
          (let* ((name (match-string-no-properties 1))
                 (relative (file-relative-name file source-root)))
            (cl-pushnew relative (gethash name origins) :test #'equal)))))
    (let (entries)
      (maphash
       (lambda (name files)
         (push (cons name (sort files #'string<)) entries))
       origins)
      (sort entries (lambda (left right) (string< (car left) (car right)))))))

(defun emaxx-generate-gnu-c-defsym-manifest (source-root output-file)
  "Write GNU C DEFSYM names from SOURCE-ROOT to OUTPUT-FILE."
  (let ((entries (emaxx--gnu-c-defsyms source-root)))
    (with-temp-buffer
      (insert "// @generated by compat/generate_gnu_c_defsym_manifest.el.\n")
      (insert "// Source contract: GNU Emacs 30.2 src/*.c DEFSYM declarations.\n")
      (insert "// Regenerate when the compatibility oracle version changes.\n\n")
      (insert "#[cfg_attr(not(test), allow(dead_code))]\n")
      (insert "#[derive(Clone, Copy, Debug)]\n")
      (insert "pub(crate) struct GnuCDefsym {\n")
      (insert "    pub(crate) name: &'static str,\n")
      (insert "    pub(crate) origins: &'static str,\n")
      (insert "}\n\n")
      (insert "#[rustfmt::skip]\n")
      (insert "pub(crate) const GNU_C_DEFSYMS: &[GnuCDefsym] = &[\n")
      (dolist (entry entries)
        (insert (format "    GnuCDefsym { name: %S, origins: %S },\n"
                        (car entry)
                        (mapconcat #'identity (cdr entry) ", "))))
      (insert "];\n")
      (write-region (point-min) (point-max) output-file))))

(provide 'generate-gnu-c-defsym-manifest)

;;; generate_gnu_c_defsym_manifest.el ends here
