;;; generate_builtin_arities.el --- Generate GNU primitive arity manifest -*- lexical-binding: t; -*-

;; Usage:
;;   emacs -Q --batch -l compat/generate_builtin_arities.el \
;;     --eval '(emaxx-generate-builtin-arities "src/lisp" "src/lisp/primitives/generated_builtin_arities.rs")'

;;; Code:

(require 'cl-lib)

(defun emaxx--rust-string-literal (value)
  "Return VALUE encoded as a single-line Rust string literal."
  (concat
   "\""
   (mapconcat
    (lambda (character)
      (pcase character
        (?\\ "\\\\")
        (?\" "\\\"")
        (?\n "\\n")
        (?\r "\\r")
        (?\t "\\t")
        (?\0 "\\0")
        ((pred (lambda (value) (or (< value 32) (= value 127))))
         (format "\\u{%x}" character))
        (_ (char-to-string character))))
    value "")
   "\""))

(defun emaxx--gnu-c-primitive-contracts (source-root)
  "Return known-arity GNU C primitive contracts below SOURCE-ROOT.

The C-source manifest is the authoritative native boundary.  In particular,
do not infer that boundary from arbitrary Rust string literals: dispatcher
implementation files also contain condition names, variable names, and Lisp
helper names."
  (let ((manifest
         (expand-file-name
          "primitives/generated_gnu_c_primitives.rs"
          source-root))
        contracts)
    (with-temp-buffer
      (insert-file-contents manifest)
      (goto-char (point-min))
      (while
          (re-search-forward
           (concat
            "GnuCPrimitiveContract { name: \"\\([^\"]+\\)\", "
            "arity: Some((\\(-?[0-9]+\\), \\(-?[0-9]+\\))), "
            "command: \\(true\\|false\\)")
           nil t)
        (push
         (list
          (match-string-no-properties 1)
          (string-to-number (match-string-no-properties 2))
          (string-to-number (match-string-no-properties 3))
          (equal (match-string-no-properties 4) "true"))
         contracts)))
    (nreverse contracts)))

(defun emaxx-generate-builtin-arities (source-root output-file)
  "Write GNU C primitive metadata below SOURCE-ROOT to OUTPUT-FILE.

The generated GNU C-source manifest supplies the exact native boundary,
arity, and command identity.  The running GNU Emacs supplies interactive
forms for C primitives available in this build.
Generating every known-arity C primitive is safe: Emaxx consults this metadata
only after its own dispatcher has produced a native function value."
  (let ((seen (make-hash-table :test #'equal))
        entries interactive-names interactive-entries)
    (pcase-dolist
        (`(,name ,minimum ,maximum ,command)
         (emaxx--gnu-c-primitive-contracts source-root))
      (unless (gethash name seen)
        (puthash name t seen)
        (push (list name minimum maximum) entries)
        (when command
          (push name interactive-names))
        (let ((symbol (intern-soft name)))
          (when (and symbol
                     (fboundp symbol)
                     (subrp (symbol-function symbol))
                     (not (and (fboundp 'subr-native-elisp-p)
                               (subr-native-elisp-p
                                (symbol-function symbol)))))
            (when-let ((interactive
                        (interactive-form (symbol-function symbol))))
              (let ((form (prin1-to-string interactive)))
                (unless (string-match-p
                         "[\0-\x08\x0b\x0c\x0e-\x1f]" form)
                  (push (list name form)
                        interactive-entries))))))))
    (setq entries (sort entries (lambda (left right)
                                  (string< (car left) (car right)))))
    (setq interactive-entries
          (sort interactive-entries
                (lambda (left right) (string< (car left) (car right)))))
    (setq interactive-names (sort interactive-names #'string<))
    (with-temp-file output-file
      (insert "// @generated by compat/generate_builtin_arities.el using GNU Emacs.\n")
      (insert "// Regenerate when the compatibility oracle version changes.\n\n")
      (insert "#[rustfmt::skip]\n")
      (insert "const GENERATED_BUILTIN_ARITIES: &[(&str, i64, i64)] = &[\n")
      (dolist (entry entries)
        (pcase-let ((`(,name ,minimum ,maximum) entry))
          (insert (format "    (%S, %d, %d),\n"
                          name minimum
                          (cond ((integerp maximum) maximum)
                                ((eq maximum 'many) -1)
                                (t -2))))))
      (insert "];\n\n")
      (insert "pub(super) fn generated_builtin_arity(name: &str) -> Option<(i64, i64)> {\n")
      (insert "    let index = GENERATED_BUILTIN_ARITIES\n")
      (insert "        .binary_search_by_key(&name, |(candidate, _, _)| *candidate)\n")
      (insert "        .ok()?;\n")
      (insert "    let (_, minimum, maximum) = GENERATED_BUILTIN_ARITIES[index];\n")
      (insert "    Some((minimum, maximum))\n")
      (insert "}\n\n")
      (insert "#[rustfmt::skip]\n")
      (insert "const GENERATED_BUILTIN_COMMANDS: &[&str] = &[\n")
      (dolist (name interactive-names)
        (insert (format "    %S,\n" name)))
      (insert "];\n\n")
      (insert "pub(super) fn generated_builtin_command_p(name: &str) -> bool {\n")
      (insert "    GENERATED_BUILTIN_COMMANDS.binary_search(&name).is_ok()\n")
      (insert "}\n\n")
      (insert "#[rustfmt::skip]\n")
      (insert "const GENERATED_BUILTIN_INTERACTIVE_FORMS: &[(&str, &str)] = &[\n")
      (dolist (entry interactive-entries)
        (pcase-let ((`(,name ,form) entry))
          (insert (format "    (%S, %s),\n"
                          name
                          (emaxx--rust-string-literal form)))))
      (insert "];\n\n")
      (insert "pub(super) fn generated_builtin_interactive_form(name: &str) -> Option<&'static str> {\n")
      (insert "    let index = GENERATED_BUILTIN_INTERACTIVE_FORMS\n")
      (insert "        .binary_search_by_key(&name, |(candidate, _)| *candidate)\n")
      (insert "        .ok()?;\n")
      (insert "    Some(GENERATED_BUILTIN_INTERACTIVE_FORMS[index].1)\n")
      (insert "}\n"))))

(provide 'generate_builtin_arities)

;;; generate_builtin_arities.el ends here
