;;; bench.el --- bytecode benchmarks -*- lexical-binding: t; -*-
(defun bench-fib (n)
  (if (< n 2) n (+ (bench-fib (- n 1)) (bench-fib (- n 2)))))
(defun bench-loop-sum (n)
  (let ((acc 0) (i 0))
    (while (< i n) (setq acc (+ acc i)) (setq i (1+ i)))
    acc))
(defun bench-list-build (n)
  (let ((acc nil) (i 0))
    (while (< i n) (setq acc (cons i acc)) (setq i (1+ i)))
    (nreverse acc)))
(defun bench-assq-scan (alist keys)
  (let ((hits 0))
    (dolist (k keys hits)
      (when (assq k alist) (setq hits (1+ hits))))))
(defun bench-string-ops (n)
  (let ((s "") (i 0))
    (while (< i n)
      (setq s (concat "x" s))
      (setq i (1+ i)))
    (length s)))
(provide 'bench)
