(let ((case-fold-search nil)
      (answers nil))
  (with-temp-buffer
    (let* ((parent (make-syntax-table))
           (child (make-char-table 'syntax-table nil))
           (descriptor (cons 1 nil))
           (categories (make-category-table)))
      (set-char-table-parent child parent)
      (set-syntax-table child)
      (set-category-table categories)
      (define-category ?x "snapshot category" categories)
      (dolist (character '(?a ?\u03a9))
        (set-char-table-range parent character descriptor)
        (modify-category-entry character ?x categories))
      (insert "a\u03a9")
      (goto-char (point-min))
      ;; Warm both caches, including a shared descriptor and category set.
      (dotimes (_ 2)
        (push (list (looking-at "\\w") (looking-at "\\cx")) answers))
      ;; The leaf identities stay fixed while their contents change.
      (setcar descriptor 2)
      (aset (aref categories ?a) ?x nil)
      (push (list (looking-at "\\w") (looking-at "\\cx")) answers)
      (forward-char)
      (push (looking-at "\\w") answers)
      ;; Disconnect the cached graph, collect, and allocate new payloads.
      ;; Validation must reject the changed edge before reading old nodes.
      (dolist (character '(?a ?\u03a9))
        (set-char-table-range parent character (cons 1 nil)))
      (setq descriptor nil)
      (garbage-collect)
      (dotimes (index 600) (make-vector (+ 1 (% index 9)) index))
      (push (looking-at "\\w") answers)
      (modify-syntax-entry ?\u03a9 "w" parent)
      (push (looking-at "\\w") answers)
      (goto-char (point-min))
      (modify-category-entry ?a ?x categories)
      (push (looking-at "\\cx") answers)))
  (nreverse answers))
