(defun record-purecopy-probe-149 ()
  (interactive)
  (let ((report (getenv "EMAXX_RECORD_PROBE_REPORT")))
    (condition-case err
        (let ((result (let ((trigger (propertize "copy-trigger-151" 'face 'bold)) results)
  (dolist (kind '(vector record))
    (let* ((original (if (eq kind 'vector)
                         (vector trigger (make-string 37 ?x))
                       (record 'copy-mutation-163 trigger (make-string 37 ?x))))
           (slot (if (eq kind 'vector) 1 2))
           (callbacks 0)
           copied)
      (let ((purify-flag t)
            (message-log-max nil)
            (inhibit-message nil)
            (clear-message-function nil)
            (set-message-function
             (lambda (_message)
               (setq callbacks (1+ callbacks))
               (aset original slot "changed-source-167")
               nil)))
        (setq copied (purecopy original)))
      (push (list kind callbacks (aref original slot) (aref copied slot)) results)))
  (nreverse results))
))
          (with-temp-file report (prin1 result (current-buffer)))
          (kill-emacs 0))
      (error
       (with-temp-file report (prin1 err (current-buffer)))
       (kill-emacs 2)))))
(global-set-key (kbd "C-c r") 'record-purecopy-probe-149)
(switch-to-buffer "*record-purecopy-ready*")
(insert "record-purecopy-ready")
(set-buffer-modified-p nil)
