(defun record-purecopy-probe-149 ()
  (interactive)
  (let ((report (getenv "EMAXX_RECORD_PROBE_REPORT")))
    (condition-case err
        (let ((result (let (results)
  (dolist (mode '(enable disable swap))
    (let* ((old-cache (make-hash-table :test 'equal))
           (new-cache (make-hash-table :test 'equal))
           (original (vector (propertize "flag-trigger-173" 'face 'bold)
                             (make-string 53 ?a) (make-string 53 ?a)))
           (callbacks 0)
           copied)
      (let ((purify-flag (if (eq mode 'enable) t old-cache))
            (message-log-max nil)
            (inhibit-message nil)
            (clear-message-function nil)
            (set-message-function
             (lambda (_message)
               (setq callbacks (1+ callbacks))
               (setq purify-flag (if (eq mode 'disable) nil new-cache))
               (garbage-collect)
               nil)))
        (setq copied (purecopy original)))
      (push (list mode callbacks (equal copied original)
                  (eq (aref copied 1) (aref copied 2))
                  (hash-table-count old-cache) (hash-table-count new-cache)
                  (eq (gethash copied new-cache) copied)
                  (text-properties-at 0 (aref copied 0))) results)))
  (nreverse results))
))
          (with-temp-file report (prin1 result (current-buffer)))
          (kill-emacs 0))
      (error
       (with-temp-file report (prin1 err (current-buffer)))
       (kill-emacs 2)))))
(global-set-key (kbd "C-c r") 'record-purecopy-probe-149)
(switch-to-buffer "*record-purecopy-ready*")
(insert "record-purecopy-ready")
(set-buffer-modified-p nil)
