(let ((source (make-vector 130 nil))
      (trigger (propertize "copy-trigger-151" 'face 'bold))
      results)
  (dotimes (index 129)
    (aset source index (make-string (+ 30 (% index 41)) (+ 65 (% index 26)))))
  (aset source 129 trigger)
  (dolist (kind '(vector list record bytecode interpreted))
    (let* ((callbacks 0)
           (original
            (cond
             ((eq kind 'vector) source)
             ((eq kind 'list) (append source nil))
             ((eq kind 'record) (apply #'record 'copy-record-157 (append source nil)))
             ((eq kind 'bytecode)
              (make-byte-code 0 (unibyte-string 192 135) source 1 trigger))
             (t
              (make-interpreted-closure nil (list (list 'quote source)) nil trigger))))
           copied)
      (let ((purify-flag t)
            (message-log-max nil)
            (inhibit-message nil)
            (clear-message-function nil)
            (set-message-function
             (lambda (_message)
               (setq callbacks (1+ callbacks))
               (garbage-collect)
               nil)))
        (setq copied (purecopy original)))
      (let* ((values
              (cond
               ((eq kind 'vector) (append copied nil))
               ((eq kind 'list) copied)
               ((eq kind 'record)
                (mapcar (lambda (index) (aref copied (1+ index))) (number-sequence 0 129)))
               ((eq kind 'bytecode) (append (aref copied 2) nil))
               (t (append (funcall copied) nil))))
             (distinct t)
             (index 0))
        (dolist (value values)
          (when (eq value (aref source index)) (setq distinct nil))
          (setq index (1+ index)))
        (push (list kind callbacks (length values)
                    (equal values (append source nil))
                    (not (eq original copied)) distinct
                    (text-properties-at 0 (car (last values)))) results))))
  (dolist (kind '(vector record))
    (let* ((original (if (eq kind 'vector)
                         (vector trigger (make-string 37 ?x))
                       (record 'copy-mutation-163 trigger (make-string 37 ?x))))
           (slot (if (eq kind 'vector) 1 2))
           (callbacks 0)
           copied)
      (let ((purify-flag t)
            (message-log-max nil)
            (inhibit-message nil)
            (clear-message-function nil)
            (set-message-function
             (lambda (_message)
               (setq callbacks (1+ callbacks))
               (aset original slot "changed-source-167")
               (garbage-collect)
               nil)))
        (setq copied (purecopy original)))
      (push (list kind callbacks (aref original slot) (aref copied slot)) results)))
  (nreverse results))
