(let ((message-log-max t)
      (messages-buffer-name "*record-message-probe*")
      (text-quoting-style 'straight)
      (inhibit-message t)
      (last-coding-system-used 'record-coding-sentinel)
      (coding-system-for-write 'utf-8))
  (let* ((purify-flag t)
         (copy (purecopy (record 'message-record (propertize "text-103" 'face 'bold)))))
    (list (aref copy 1)
          (get-buffer messages-buffer-name)
          last-coding-system-used)))
