(let (results)
  (dolist (mode '(enable disable swap))
    (let* ((old-cache (make-hash-table :test 'equal))
           (new-cache (make-hash-table :test 'equal))
           (original (vector (propertize "flag-trigger-173" 'face 'bold)
                             (make-string 53 ?a) (make-string 53 ?a)))
           (callbacks 0)
           copied)
      (let ((purify-flag (if (eq mode 'enable) t old-cache))
            (message-log-max nil)
            (inhibit-message nil)
            (clear-message-function nil)
            (set-message-function
             (lambda (_message)
               (setq callbacks (1+ callbacks))
               (setq purify-flag (if (eq mode 'disable) nil new-cache))
               (garbage-collect)
               nil)))
        (setq copied (purecopy original)))
      (push (list mode callbacks (equal copied original)
                  (eq (aref copied 1) (aref copied 2))
                  (hash-table-count old-cache) (hash-table-count new-cache)
                  (eq (gethash copied new-cache) copied)
                  (text-properties-at 0 (aref copied 0))) results)))
  (nreverse results))
