(let ((first (record 'property-record-113 19))
      (second (record 'property-record-113 19))
      (property 'property-key-127))
  (with-temp-buffer
    (insert "abcdefghi")
    (dotimes (index 9)
      (put-text-property (1+ index) (+ index 2) property
                         (if (and (>= index 4) (< index 7)) second first)))
    (let ((text (buffer-string)))
      (list
       (list (eq first second) (equal first second))
       (mapcar (lambda (position)
                 (next-single-property-change position property nil (point-max)))
               '(1 2 4 5 7 8 9))
       (mapcar (lambda (position)
                 (previous-single-property-change position property nil (point-min)))
               '(10 9 8 7 5 4 2))
       (text-property-any 1 (point-max) property first)
       (text-property-not-all 1 (point-max) property first)
       (eq (get-text-property 1 property) (get-text-property 8 property))
       (eq (get-text-property 1 property) (get-text-property 5 property))
       (mapcar (lambda (position)
                 (next-single-property-change position property text (length text)))
               '(0 1 3 4 6 7 8))
       (eq (get-text-property 0 property text) first)
       (equal-including-properties text (copy-sequence text))))))
