(let* ((print-circle t)
       (shared (vector 'payload-29 (cons 11 13)))
       (descriptor (record 'record-descriptor-7 'public-class-29))
       (object (record descriptor shared shared))
       (copy (copy-sequence object))
       (self (make-record 'self-31 2 nil))
       (other (make-record 'self-31 2 nil))
       (table (make-hash-table :test 'equal))
       result)
  (puthash object 'found-47 table)
  (setq result
        (list (recordp object) (arrayp object) (vectorp object)
              (length object) (type-of object) (cl-type-of object)
              (eq object copy) (equal object copy)
              (eq (aref object 1) (aref copy 2)) (gethash copy table)))
  (aset copy 0 'renamed-53)
  (aset descriptor 1 'retyped-59)
  (setq result (append result (list (type-of object) (type-of copy))))
  (aset self 1 self)
  (aset self 2 (vector self))
  (aset other 1 other)
  (aset other 2 (vector other))
  (setq result (append result (list (equal self other)
                                   (equal-including-properties self other)
                                   (prin1-to-string self))))
  (let* ((decoded (read (prin1-to-string self)))
         (snapshot (copy-sequence self)))
    (setq result (append result
                        (list (eq decoded (aref decoded 1))
                              (eq decoded (aref (aref decoded 2) 0))
                              (eq self (aref snapshot 1))))))
  (aset other 2 [different-61])
  (setq result (append result (list (equal self other))))
  (garbage-collect)
  (append result (list (eq self (aref self 1)) (aref (aref object 1) 0))))
