;; The same input is run by each editor through its ordinary batch entry.
(prin1
 (list
  (let* ((shared (cons 'start nil))
         (a (vector shared shared))
         (b (cons shared a)))
    (setcdr shared b)
    (garbage-collect)
    (setcar (aref a 1) 37)
    (prog1
        (list (eq (aref a 0) (aref a 1))
              (eq (cdr shared) b)
              (car (car b)))
      (setcdr shared nil)))
  (let* ((definition (cons 'ordinary 'list))
         (form (list 'compact-mutable-macro 17 'payload)))
    (fset 'compact-mutable-macro definition)
    (let ((before (macroexpand form)))
      (setcar definition 'macro)
      (list (eq before form) (macroexpand form))))
  (let* ((parent (make-sparse-keymap))
         (child (make-keymap))
         (table (make-char-table 'keymap)))
    (define-key parent [f8] 'parent-command)
    (set-char-table-range table 65 'table-command)
    (lookup-key child "A")
    (setcdr child (cons table parent))
    (list (eq (keymap-parent child) parent)
          (lookup-key child "A")
          (lookup-key child [f8])))))
(terpri)
