(mapcar
 (lambda (reader)
   (let* ((chars (string-to-list "(#:one [#:two \"text\"] #s(kind #:three) #1=(#:cycle . #1#)) tail"))
          (count 0)
          (source (lambda (&optional character)
                    (if character (push character chars)
                      (setq count (1+ count))
                      (when (= (% count 7) 0) (garbage-collect))
                      (pop chars))))
          (form (funcall reader source))
          (cycle (nth 3 form)))
     (list (length form)
           (symbol-name (bare-symbol (car form)))
           (symbol-name (bare-symbol (aref (nth 1 form) 0)))
           (aref (nth 1 form) 1)
           (symbol-name (aref (nth 2 form) 1))
           (symbol-name (bare-symbol (car cycle)))
           (eq cycle (cdr cycle))
           (concat chars))))
 '(read read-positioning-symbols))
