(mapcar
 (lambda (reader)
   (let ((table (make-hash-table :test 'eq :weakness 'key)))
     (funcall
      (lambda ()
        (let* ((characters (string-to-list "(#:temporary [#:nested])"))
               (stream (lambda (&optional character)
                         (if character (push character characters)
                           (pop characters))))
               (form (funcall reader stream)))
          (puthash form t table)
          (puthash (car form) t table)
          (puthash (aref (nth 1 form) 0) t table)
          (garbage-collect)
          (unless (= (hash-table-count table) 3)
            (error "Reader result was reclaimed while live")))))
     (garbage-collect)
     (hash-table-count table)))
 '(read read-positioning-symbols))
